### ISSUE TITLE
Change status_code to statusCode?

### ISSUE THREAD

**Issue by RafaelPlantard** [laravelista/Syndra#5]
Is there possible change structure of all error messages?

**Comment by mabasic** [comment]
Can you explain a bit more on what is the issue?

**Comment by RafaelPlantard** [comment]
Nowadays, the JSON returned by:
`$this->syndra->respondForbidden();`
is:

```
{
  "error": {
    "message": "Forbidden",
    "status_code": 403
  }
}
```

Is possible change to:

```
{
  "error": {
    "message": "Forbidden",
    "statusCode": 403
  }
}
```

**Comment by mabasic** [comment]
Is this really a big deal :) If you want to change it, you can always extend Syndra and change `respondWithError` method to return the desired response.

Is there a specific scenario where this is making a problem for you?

**Comment by RafaelPlantard** [comment]
I would like do it without have to extend the Syndra class, is possible?

**Comment by mabasic** [comment]
Sorry for the long wait. Currently it is not possible.
